### ISSUE TITLE
`useTypedLoaderData` Syntax Error during another Error

### ISSUE THREAD

**Issue by jmaldon1** [kiliman/remix-typedjson#16]
Trying to reproduce with a minimal example:

```typescript
export const loader = async ({
    request,
  }: LoaderArgs): Promise<TypedJsonResponse<LoaderData>> => {
  
    const data = {
      date: new Date()
    };
  
    return typedjson(data);
};


export default function Dashboard(): JSX.Element {
  const loaderData = useTypedLoaderData<typeof loader>();
  const { date } = loaderData;
  // Purposefully throw an error to show issue
  throw new Error("TEST")
  return null;
}

```

Error message in browser console window:

```
Uncaught SyntaxError: Unexpected identifier 'Nov'
```

When checking the file its talking about in Sources tab
You'll see something like this in the file:

```
'routeData':{'routes/dashboard': {'date':Thu Nov 03 2022 11:04:25 GMT-0400 (Eastern Daylight Time)}}'
```

Seems like the `typedjson` is causing syntax errors somewhere due to the type conversions?

**Comment by jmaldon1** [comment]
If i replace `useTypedLoaderData` with `useLoaderData` this syntax error goes way

**Comment by kiliman** [comment]
I'm not seeing the error. 

> Note: I import Remix from a single file (which also overrides `json` and `useLoaderData` with my typed versions). See https://github.com/kiliman/rmx-cli#-gen-remix

Anyway, I'm getting the `ErrorBoundary` as expected. 

A couple of things I noticed is that 1) You're explicitly typing your loader function return instead of letting TypeScript infer. 2) You use type `LoaderData`, but I don't see it in your example.

Can you provide a repo that shows the error you're having?

```ts
import { json, useLoaderData, type LoaderArgs } from '~/remix'

export async function loader({ request }: LoaderArgs) {
  return json({ date: new Date() })
}

export default function Index() {
  const loaderData = useLoaderData<typeof loader>()
  throw new Error('oops!')
  return (
    <>
      <h1>Data</h1>
      <pre>{JSON.stringify(loaderData, null, 2)}</pre>
    </>
  )
}

export function ErrorBoundary({ error }: { error: Error }) {
  return (
    <>
      <h1>Error</h1>
      <pre>{error.message}</pre>
    </>
  )
}
```
<img width="338" alt="image" src="https://user-images.githubusercontent.com/47168/199785034-039b7813-7fdb-465a-97b6-03c4b23b4f81.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/47168/199783709-1cdda86a-d0a1-4147-bce9-44a18d89d648.png">

**Comment by jmaldon1** [comment]
So weird, its bugged on my repo (its a private repo, so its hard to share it) and I'm having trouble recreating on a fresh repo. I was able to narrow it down to the `<Scripts />` tag in the `root.tsx` file. But i'm still trying to recreate it.

**Comment by jmaldon1** [comment]
@kiliman https://github.com/jmaldon1/typedjson-error-repro

Here we go, I basically deleted everything from my repo and tried to get to the minimum code with the error.

**Comment by kiliman** [comment]
Interesting. When Remix SSRs the route, it includes the loader data in the script along with the HTML, so during hydration it can re-render on the client. However, it's odd that it's embedding the converted loader data (from `useTypedLoaderData`) instead of just the data from the loader itself. Which in this case looks like, and would not cause the error.
```json
{"date":"2022-11-03T20:57:56.527Z","__meta__":{"date":"date"}}
```
This only appears to happen during SSR and not when Remix fetches client side loaders.

The only big difference between your code and my repro is that you're using Emotion. Not sure if that's the culprit or not.

**Comment by jmaldon1** [comment]
Updated to `"@remix-run/dev": "^1.7.5",` and i think it fixed it lol
